server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/employee/**
        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**
    loadbalancer:
      ribbon:
        enabled: true
  zipkin:
    base-url: http://localhost:9411/
    locator:
      discovery:
        enabled: true
  application:
    name: api-gateway



# 3.Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@ben450:9010/eureka,http://eureka:eureka@ben450:9011/eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
    hostname: ${spring.cloud.client.ip-address}
